package hooks

// Package hooks — opencode_plugin.go
//
// OpenCode uses a JS/TS plugin API rather than a CLI hook. The deny path is
// NOT exit-code-based: the plugin must `throw new Error(...)` inside the
// `tool.execute.before` hook to abort the tool call.
//
// This installer ships a JS plugin template to
// ~/.config/opencode/plugins/beekeeper.js that shells out to
// `beekeeper check --hook opencode` and throws on a non-zero exit code.
//
// CAVEATS (documented in install output and the support matrix):
//   - T-10-19 (accepted): The plugin does NOT catch subagent `task` calls (#5894).
//   - The plugin does NOT catch MCP tool calls from the plugin runtime (#2319).
//   - These limitations are upstream OpenCode constraints, not Beekeeper bugs.
//   - MCP tool calls from the agent's perspective route through the gateway.

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// openCodePluginDir returns the path to the OpenCode plugins directory.
func openCodePluginDir(homeDir string) string {
	return homeDir + "/.config/opencode/plugins"
}

// openCodePluginPath returns the path to the beekeeper plugin file.
func openCodePluginPath(pluginDir string) string {
	return filepath.Join(pluginDir, "beekeeper.js")
}

// openCodePluginTemplate is the JS plugin content written to beekeeper.js.
// It implements the tool.execute.before hook: shells to beekeeper check and
// throws on non-zero exit (deny), letting the tool proceed on exit 0 (allow).
//
// Runtime note: OpenCode uses Bun as its JS runtime. child_process.spawnSync
// is available via Bun's Node.js compatibility layer.
const openCodePluginTemplate = `// Beekeeper safety hook for OpenCode
// Generated by: beekeeper hooks install --target opencode
// Docs: https://opencode.ai/docs/plugins
//
// CAVEATS:
//   - This plugin does NOT intercept subagent 'task' calls (#5894).
//   - This plugin does NOT intercept MCP tool calls (#2319).
//   - Both are upstream OpenCode limitations. MCP tools are covered by the
//     Beekeeper MCP gateway (beekeeper gateway start).

import { spawnSync } from "child_process";

// Hook: tool.execute.before — called before every tool invocation.
// Shells to: beekeeper check --hook opencode
export default {
  tool: {
    execute: {
      before: (ctx) => { // tool.execute.before
        // Serialize the tool call context and pipe it to beekeeper check.
        const input = JSON.stringify(ctx);
        const result = spawnSync(
          "beekeeper",
          ["check", "--hook", "opencode"], // command: beekeeper check --hook opencode
          {
            input,
            encoding: "utf-8",
            timeout: 15000,
          }
        );

        // Non-zero exit = deny. Throw so OpenCode aborts the tool call.
        if (result.status !== 0) {
          const reason =
            (result.stderr && result.stderr.trim()) ||
            (result.stdout && result.stdout.trim()) ||
            "blocked by beekeeper policy";
          throw new Error("[beekeeper] tool call blocked: " + reason);
        }

        // Exit 0 = allow — return undefined (do not modify the tool call).
        return undefined;
      },
    },
  },
};
`

// openCodePluginMarker is a string that uniquely identifies a beekeeper-managed
// plugin file. Used for idempotency checks and safe uninstall.
const openCodePluginMarker = "Generated by: beekeeper hooks install --target opencode"

// installOpenCodePlugin writes beekeeper.js to pluginDir.
// Behaviour:
//   - If the file does not exist: create it.
//   - If the file already contains openCodePluginMarker: no-op (idempotent).
//   - If the file exists but is a foreign plugin: back it up and overwrite,
//     reporting the action to out.
//
// After writing, the caveats about subagent (#5894) and MCP (#2319) bypass
// are printed to out.
func installOpenCodePlugin(pluginDir string, dryRun bool, out io.Writer) error {
	pluginPath := openCodePluginPath(pluginDir)

	existing, err := os.ReadFile(pluginPath)
	switch {
	case err == nil:
		if strings.Contains(string(existing), openCodePluginMarker) {
			fmt.Fprintf(out, "OpenCode beekeeper.js already installed at %s — no change.\n", pluginPath)
			printOpenCodeCaveats(out)
			return nil
		}
		// Foreign plugin: back up and overwrite.
		if dryRun {
			fmt.Fprintf(out, "[dry-run] Would back up existing beekeeper.js (foreign plugin) and overwrite at %s\n", pluginPath)
			printOpenCodeCaveats(out)
			return nil
		}
		if err := backupSettings(pluginPath); err != nil {
			return err
		}
		fmt.Fprintf(out, "WARNING: Backed up existing beekeeper.js (foreign plugin). Installing Beekeeper plugin.\n")

	case errors.Is(err, os.ErrNotExist):
		if dryRun {
			fmt.Fprintf(out, "[dry-run] Would write OpenCode plugin to %s\n", pluginPath)
			printOpenCodeCaveats(out)
			return nil
		}

	default:
		return fmt.Errorf("opencode plugin: read %q: %w", pluginPath, err)
	}

	if dryRun {
		fmt.Fprintf(out, "[dry-run] Would write OpenCode plugin to %s\n", pluginPath)
		printOpenCodeCaveats(out)
		return nil
	}

	if err := os.MkdirAll(pluginDir, 0o755); err != nil {
		return fmt.Errorf("opencode plugin: mkdir %q: %w", pluginDir, err)
	}

	if err := writeFileAtomic(pluginPath, []byte(openCodePluginTemplate)); err != nil {
		return err
	}

	fmt.Fprintf(out, "Installed OpenCode plugin at %s\n", pluginPath)
	printOpenCodeCaveats(out)
	return nil
}

// uninstallOpenCodePlugin removes the beekeeper.js plugin from pluginDir.
// It only removes the file if it contains openCodePluginMarker; foreign plugins
// are preserved.
func uninstallOpenCodePlugin(pluginDir string, dryRun bool, out io.Writer) error {
	pluginPath := openCodePluginPath(pluginDir)

	data, err := os.ReadFile(pluginPath)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			fmt.Fprintf(out, "No OpenCode beekeeper.js found at %s — nothing to uninstall.\n", pluginPath)
			return nil
		}
		return fmt.Errorf("opencode plugin uninstall: read %q: %w", pluginPath, err)
	}

	if !strings.Contains(string(data), openCodePluginMarker) {
		fmt.Fprintf(out, "beekeeper.js at %s is not a beekeeper plugin — not removed (foreign plugin preserved).\n", pluginPath)
		return nil
	}

	if dryRun {
		fmt.Fprintf(out, "[dry-run] Would remove beekeeper OpenCode plugin at %s\n", pluginPath)
		return nil
	}

	if err := os.Remove(pluginPath); err != nil {
		return fmt.Errorf("opencode plugin uninstall: remove %q: %w", pluginPath, err)
	}

	fmt.Fprintf(out, "Removed OpenCode beekeeper plugin at %s\n", pluginPath)
	return nil
}

// printOpenCodeCaveats prints the known limitations of the OpenCode plugin
// to out so users understand what is and is not protected.
func printOpenCodeCaveats(out io.Writer) {
	fmt.Fprintf(out, "\nCAVEAT: The OpenCode plugin does NOT intercept:\n")
	fmt.Fprintf(out, "  - Subagent 'task' calls (OpenCode #5894 — upstream limitation)\n")
	fmt.Fprintf(out, "  - MCP tool calls from within the plugin runtime (OpenCode #2319)\n")
	fmt.Fprintf(out, "For MCP tool protection, run the Beekeeper MCP gateway:\n")
	fmt.Fprintf(out, "  beekeeper gateway start\n\n")
}
