package coveragegate

import (
	"math"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestPackageCoverageParsesProfile(t *testing.T) {
	// Two packages: pkga has 10/10 stmts covered (100%), pkgb has 3/10 (30%).
	profile := strings.Join([]string{
		"mode: set",
		ModulePath + "/internal/pkga/a.go:1.1,3.2 6 1",
		ModulePath + "/internal/pkga/a.go:5.1,6.2 4 1",
		ModulePath + "/internal/pkgb/b.go:1.1,2.2 3 1",
		ModulePath + "/internal/pkgb/b.go:4.1,9.2 7 0",
		"",
	}, "\n")

	cov, err := PackageCoverage(strings.NewReader(profile))
	if err != nil {
		t.Fatalf("PackageCoverage: %v", err)
	}
	if got := cov["internal/pkga"]; math.Abs(got-100) > 0.01 {
		t.Errorf("pkga = %.2f, want 100", got)
	}
	if got := cov["internal/pkgb"]; math.Abs(got-30) > 0.01 {
		t.Errorf("pkgb = %.2f, want 30", got)
	}
}

func TestPackageCoverageMalformed(t *testing.T) {
	for _, bad := range []string{
		"mode: set\ngithub.com/x/y/f.go:1.1,2.2 notanumber 1\n",
		"mode: set\nthis line has no colon and wrong fields\n",
	} {
		if _, err := PackageCoverage(strings.NewReader(bad)); err == nil {
			t.Errorf("expected error for malformed profile %q", bad)
		}
	}
}

func TestFloorForOverridesDefaultAndExempt(t *testing.T) {
	if f, exempt := FloorFor("internal/audit"); exempt || f != 85 {
		t.Errorf("internal/audit floor = %v exempt=%v, want 85 false", f, exempt)
	}
	if f, exempt := FloorFor("internal/policyloader"); exempt || f != defaultFloor {
		t.Errorf("internal/policyloader floor = %v exempt=%v, want %v false", f, exempt, defaultFloor)
	}
	if _, exempt := FloorFor("internal/sentry/windows"); !exempt {
		t.Error("internal/sentry/windows should be exempt")
	}
	if _, exempt := FloorFor("cmd/beekeeper"); !exempt {
		t.Error("cmd/beekeeper should be exempt")
	}
}

func TestFloorViolationsFlagsAndSkips(t *testing.T) {
	cov := map[string]float64{
		"internal/audit":          84.9, // below the 85 floor -> violation
		"internal/baseline":       97.2, // above 92 floor -> ok
		"internal/quarantine":     80.1, // above default 80 -> ok
		"internal/sentry/windows": 22.8, // exempt -> skipped
		"cmd/beekeeper":           25.2, // exempt -> skipped
	}
	v := FloorViolations(cov)
	if len(v) != 1 {
		t.Fatalf("expected exactly 1 violation, got %d: %+v", len(v), v)
	}
	if v[0].Package != "internal/audit" || v[0].Floor != 85 {
		t.Errorf("unexpected violation: %+v", v[0])
	}
}

func TestFloorViolationsRoundingTolerance(t *testing.T) {
	// 84.96 rounds to 85.0 and must NOT trip the 85 floor (float artifact guard).
	cov := map[string]float64{"internal/audit": 84.96}
	if v := FloorViolations(cov); len(v) != 0 {
		t.Errorf("84.96 should round to 85.0 and pass, got violations: %+v", v)
	}
}

// TestCoverageFloor enforces the statement-coverage floor against a coverprofile
// generated by a prior `go test ./... -coverprofile`. It is SKIPPED unless
// BEEKEEPER_COVERPROFILE points at that profile, so the normal unit run never
// re-runs the whole suite from inside this test. The Makefile `coverage` target
// and the CI coverage-floor job set the env var.
func TestCoverageFloor(t *testing.T) {
	profile := os.Getenv("BEEKEEPER_COVERPROFILE")
	if profile == "" {
		t.Skip("set BEEKEEPER_COVERPROFILE to a coverprofile to enforce the floor (see Makefile `coverage`)")
	}
	// `go test` runs with cwd set to the package dir, so resolve a relative
	// profile path against the module root (lets the Makefile/CI pass a bare name).
	if !filepath.IsAbs(profile) {
		if root, err := ModuleRoot("."); err == nil {
			profile = filepath.Join(root, profile)
		}
	}
	violations, err := CheckFloorProfile(profile)
	if err != nil {
		t.Fatalf("checking coverage floor: %v", err)
	}
	for _, v := range violations {
		t.Errorf("coverage floor: %s is %.1f%%, below its %.0f%% floor", v.Package, v.Percent, v.Floor)
	}
	if len(violations) > 0 {
		t.Fatalf("%d package(s) below their coverage floor; raise tests or justify lowering the floor in floor.go", len(violations))
	}
}
