//go:build linux

// Code generated by bpf2go; DO NOT EDIT manually.
// Run go generate ./internal/sentry/linux/ on Linux CI to regenerate real bindings.
//
// This committed file is a FAIL-CLOSED loader stub (Phase 20, SENT-11). The real
// bytecode is CI-generated at build time, NEVER committed, and NEVER compiled at
// runtime (CLAUDE.md eBPF constraint). When bytecode is absent (Windows/macOS or
// a local build without `go generate`), loadBeekeeperDNSObjects returns a clear
// error so DNS ingestion fails closed (absent), never silently broken.

package linux

import (
	"errors"

	"github.com/cilium/ebpf"
)

type BeekeeperDNSObjects struct {
	BeekeeperDNSPrograms
	BeekeeperDNSMaps
}

func (o *BeekeeperDNSObjects) Close() error {
	return nil
}

type BeekeeperDNSPrograms struct {
	KprobeUdpSendmsg *ebpf.Program `ebpf:"kprobe__udp_sendmsg"`
	KprobeTcpSendmsg *ebpf.Program `ebpf:"kprobe__tcp_sendmsg"`
}

func (p *BeekeeperDNSPrograms) Close() error {
	return nil
}

type BeekeeperDNSMaps struct {
	Events *ebpf.Map `ebpf:"dns_events"`
}

func (m *BeekeeperDNSMaps) Close() error {
	return nil
}

func loadBeekeeperDNSObjects(objs *BeekeeperDNSObjects, opts *ebpf.CollectionOptions) error {
	return errors.New("bpf2go: run go generate ./internal/sentry/linux/ on Linux to generate real bindings")
}
