//go:build linux

// Code generated by bpf2go; DO NOT EDIT manually.
// Run go generate ./internal/sentry/linux/ on Linux CI to regenerate real bindings.

package linux

import (
	"errors"

	"github.com/cilium/ebpf"
)

type BeekeeperNetObjects struct {
	BeekeeperNetPrograms
	BeekeeperNetMaps
}

func (o *BeekeeperNetObjects) Close() error {
	return nil
}

type BeekeeperNetPrograms struct {
	KprobeTcpConnect *ebpf.Program `ebpf:"kprobe__tcp_connect"`
}

func (p *BeekeeperNetPrograms) Close() error {
	return nil
}

type BeekeeperNetMaps struct {
	Events *ebpf.Map `ebpf:"network_events"`
}

func (m *BeekeeperNetMaps) Close() error {
	return nil
}

func loadBeekeeperNetObjects(objs *BeekeeperNetObjects, opts *ebpf.CollectionOptions) error {
	return errors.New("bpf2go: run go generate ./internal/sentry/linux/ on Linux to generate real bindings")
}
