//go:build linux

// Code generated by bpf2go; DO NOT EDIT manually.
// Run go generate ./internal/sentry/linux/ on Linux CI to regenerate real bindings.

package linux

import (
	"errors"

	"github.com/cilium/ebpf"
)

type BeekeeperExecObjects struct {
	BeekeeperExecPrograms
	BeekeeperExecMaps
}

func (o *BeekeeperExecObjects) Close() error {
	return nil
}

type BeekeeperExecPrograms struct {
	TracepointSchedSchedProcessExec *ebpf.Program `ebpf:"tracepoint__sched__sched_process_exec"`
}

func (p *BeekeeperExecPrograms) Close() error {
	return nil
}

type BeekeeperExecMaps struct {
	Events *ebpf.Map `ebpf:"process_events"`
}

func (m *BeekeeperExecMaps) Close() error {
	return nil
}

func loadBeekeeperExecObjects(objs *BeekeeperExecObjects, opts *ebpf.CollectionOptions) error {
	return errors.New("bpf2go: run go generate ./internal/sentry/linux/ on Linux to generate real bindings")
}
