//go:build fuzz

package catalog

import "testing"

// FuzzParseCatalogFile runs the catalog parser against fuzz-generated bytes.
// Contract: ParseCatalogFile must never panic regardless of input shape.
// Returning an error for malformed bytes is correct behavior; panicking is a
// fail-open vector because a poisoned catalog feed could crash the evaluator
// before it can block the tool call (T-02-09-01).
func FuzzParseCatalogFile(f *testing.F) {
	// Seed corpus: valid catalog, bare top-level array (invalid schema), unknown
	// schema_version, truncated JSON mid-field, and a deeply nested object that
	// exercises the decoder's recursion depth handling.
	f.Add([]byte(`{"schema_version":"0.1.0","entries":[]}`))
	f.Add([]byte(`[{"ecosystem":"npm","package":"foo","id":"x","name":"x","severity":"high"}]`))
	f.Add([]byte(`{"schema_version":"v99","entries":[]}`))
	f.Add([]byte(`{"schema_version":"0.1.0","entries":[{"id":"t","name":"t","eco`))
	f.Add([]byte(`{"schema_version":"0.1.0","entries":[{"id":"1","name":"deep","ecosystem":"npm","package":"pkg","versions":["1.0.0"],"severity":"high","catalog_source":"bumblebee","extra":{"a":{"b":{"c":{"d":{"e":"f"}}}}}}]}`))

	f.Fuzz(func(t *testing.T, data []byte) {
		cf, err := ParseCatalogFile(data)
		if err != nil {
			// An error is expected and correct for malformed or unsupported input.
			return
		}
		// A successful parse must have the supported schema version: ParseCatalogFile
		// gates via ValidateSchemaVersion, so a mismatch here would be a bug in
		// the parser, not the fuzzer input.
		if cf.SchemaVersion != SupportedSchemaVersion {
			t.Errorf("ParseCatalogFile succeeded with schema_version %q; expected %q",
				cf.SchemaVersion, SupportedSchemaVersion)
		}
	})
}
